/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.Alumno;
import clases.Materia;
import java.util.HashSet;

/**
 *
 * @author Lourdes
 */
public class menu extends javax.swing.JFrame {
public static HashSet<Alumno> registro = new HashSet<>();
public static HashSet<Materia> materia = new HashSet<>();
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_formulario = new javax.swing.JMenu();
        menuItemAlumnos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemMaterias = new javax.swing.JMenuItem();
        menu_inscripcion = new javax.swing.JMenu();
        menuItemInscripcion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_inscriptos = new javax.swing.JMenuItem();
        jMenuItem_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrows.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        escritorio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 300, 450));

        jLabel3.setFont(new java.awt.Font("Messina Sans", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Universidad de La Punta");
        escritorio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, -1));

        jLabel4.setFont(new java.awt.Font("Messina Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("(Selecciona una opción del menú)");
        escritorio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, -1));

        jLabel5.setFont(new java.awt.Font("Messina Sans", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¡Bienvenido!");
        escritorio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, -1));

        jLabel6.setFont(new java.awt.Font("Messina Sans", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de Colegio");
        escritorio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, -1));

        jLabel7.setFont(new java.awt.Font("Messina Sans", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2024©");
        escritorio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/13223142_5191466.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        escritorio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 290));

        menu_formulario.setText("Alumno");

        menuItemAlumnos.setText("Agregar Alumno");
        menuItemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnosActionPerformed(evt);
            }
        });
        menu_formulario.add(menuItemAlumnos);

        jMenuBar1.add(menu_formulario);

        jMenu1.setText("Materia");

        menuItemMaterias.setText("Agregar materias...");
        menuItemMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemMaterias);

        jMenuBar1.add(jMenu1);

        menu_inscripcion.setText("Registro");

        menuItemInscripcion.setText("Inscripción");
        menuItemInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInscripcionActionPerformed(evt);
            }
        });
        menu_inscripcion.add(menuItemInscripcion);

        jMenuBar1.add(menu_inscripcion);

        jMenu3.setText("Otro");

        jMenuItem_inscriptos.setText("Inscriptos...");
        jMenuItem_inscriptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inscriptosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_inscriptos);

        jMenuItem_Salir.setText("Salir");
        jMenuItem_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SalirActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Salir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnosView fa = new FormularioAlumnosView();
        fa.setVisible(true);
        escritorio.add(fa);
        escritorio.moveToFront(fa);
        
    }//GEN-LAST:event_menuItemAlumnosActionPerformed

    private void menuItemMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateriasView fm = new  FormularioMateriasView();
         fm.setVisible(true);
        escritorio.add(fm);
        escritorio.moveToFront(fm);
    }//GEN-LAST:event_menuItemMateriasActionPerformed

    private void menuItemInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInscripcionActionPerformed
         escritorio.removeAll();
        escritorio.repaint();
        InscripcionView iv = new InscripcionView();
        iv.setVisible(true);
        escritorio.add(iv);
        escritorio.moveToFront(iv);
    }//GEN-LAST:event_menuItemInscripcionActionPerformed

    private void jMenuItem_inscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inscriptosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InscriptosView iv = new InscriptosView();
        iv.setVisible(true);
        escritorio.add(iv);
        escritorio.moveToFront(iv);
    }//GEN-LAST:event_jMenuItem_inscriptosActionPerformed

    private void jMenuItem_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Salir;
    private javax.swing.JMenuItem jMenuItem_inscriptos;
    private javax.swing.JMenuItem menuItemAlumnos;
    private javax.swing.JMenuItem menuItemInscripcion;
    private javax.swing.JMenuItem menuItemMaterias;
    private javax.swing.JMenu menu_formulario;
    private javax.swing.JMenu menu_inscripcion;
    // End of variables declaration//GEN-END:variables
}
